#!/usr/bin/env bash
#This script displays the list of running processes
#!/bin/bash

# Print the header
printf "%-10s %-8s\n" "USER" "START"

# Get the process information
process_info=$(ps -eo user,start --sort=start_time)

# Loop through each process
while read -r line; do
  # Print the user and start time
  printf "%-10s %-8s\n" $line
done <<< "$process_info"

