#!/usr/bin/env bash
#creates tthe file /var/run/myscript.pid containing its PID
#Displays to infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SINGTERM signal 
#displays Y U no love me ?! when receiving a SIGNT signals 
#deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGTQUIT or SIDTERM signal.

terminator() 
{
	rm /var/ru/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true 
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done 

