#!/usr/bin/env bash
#creates tthe file /var/run/myscript.pid containing its PID
#Displays to infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SINGTERM signal 
#displays Y U no love me ?! when receiving a SIGNT signals 
#deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGTQUIT or SIDTERM signal.

function love() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/myscript.pid
while true ; do
    echo To infinity and beyond;
done
