#!/usr/bin/env bash
# Get the current script's PID

current_pid=$$
process_name=$(basename "$0")

for pid in $(pgrep bash); do
    if [[ $pid != $current_pid ]]; then
        process_name=$(tr '\0' ' ' < "/proc/$pid/cmdline")
        echo "$pid $process_name"
    fi
done

