#!/usr/bin/env bash
#Thanks Lord 1for today 

# Start the 4-to_infinity_and_beyond process in the background
./4-to_infinity_and_beyond &

# Store the PID of the process
PID=$(pgrep -f "4-to_infinity_and_beyond")

# Wait for a keypress to continue
read -n 1 -s -r -p "Press any key to stop the process..."

# Send the SIGTERM signal to terminate the process
kill $PID

echo "Process terminated"

