#!/usr/bin/env bash
#!/bin/bash

# Find the PID of the "4-to_infinity_and_beyond" process
PID=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$PID" ]; then
  echo "Process is not running."
else
  # Send the SIGTERM signal to stop the process
  kill "$PID"
  echo "Process terminated."
fi

